# Generated by Django 2.2.9 on 2020-01-05 16:11

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190605_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='blog_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, through='blog.BlogCategoryBlogPage', to='blog.BlogCategory'),
        ),
    ]
